name: TOML Checker
on:
  push:
    paths:
      - "embeds.toml"
jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
      - name: Install java
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: false

      - name: Clone repository 
        uses: actions/checkout@v2

      - name: Download application
        run: wget 'https://geri.dev/bloom/check.jar'

      - name: 'Verify TOML code'
        id: verify
        run: |
          echo ::set-output name=results::$(java -jar check.jar embeds.toml)

      - name: '✔️ Valid TOML Code Found'
        run: exit 0
        if: steps.verify.outputs.results == 'OK'

      - name: '❌ Invalid TOML Code Found'
        run: |
          echo ::error::Unable to parse data:
          echo '::error::${{steps.verify.outputs.results}}'
          exit 1
        if: steps.verify.outputs.results != 'OK'
